openapi: 3.0.0
info:
  title: OpenWeatherMap API
  version: '2.5'
  description: 'Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: Weather
      tags:
        - Weather endpoints
      responses: {}
      operationId: get-weather
      description: 'Access current weather data for any location on Earth including over 200,000 cities! Current weather is frequently updated based on global models and data from more than 40,000 weather stations.'
      security:
        - app_id: []
      parameters:
        - schema:
            type: string
          in: query
          name: zip
          description: '**Zip code**. Search by zip code. *Example: 95050,us*. Please note that if the country is not specified, the search uses USA as a default.'
        - schema:
            type: string
            enum:
              - standard
              - metric
              - imperial
            default: standard
          in: query
          name: units
          description: '**Units**. *Example: imperial*. Possible values: `standard`, `metric`, and `imperial`. When you do not use the `units` parameter, the format is `standard` by default.'
        - $ref: '#/components/parameters/lon'
        - schema:
            type: string
            default: json
            enum:
              - json
              - xml
              - html
          in: query
          name: mode
          description: '**Mode*. *Example: html. Determines the format of the response. Possible values are `json`, `xml`, and `html`. If the mode parameter is empty, the format is `json` by default.'
    parameters: []
components:
  parameters:
    lon:
      name: lon
      in: query
      description: '**Longitude**. *Example: 139*. Longitude coordinate of the location of your interest. Must use with `lat`.'
      schema:
        type: string
  schemas: {}
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
tags:
  - name: Weather endpoints
